services:
  app:
    build:
      context: .
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
      PORT: 3000
      DATABASE_URL: mysql://root:tyronne2001!@copart-db-1:3306/esquema # Use 'db' as the hostname because Docker resolves it to the MySQL container
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - sameNetworkAsMysql

  db:
    image: mysql:8.0.40
    environment:
      MYSQL_DATABASE: esquema
      MYSQL_ROOT_PASSWORD: tyronne2001! # Use this to configure the root password
    ports:
      - "3309:3306" # Use port 3309 on the host to avoid conflicts
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sameNetworkAsMysql

networks:
  sameNetworkAsMysql:
    driver: bridge

volumes:
  db-data:
